// Package openapispec GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package openapispec

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/audit": {
            "post": {
                "description": "This endpoint audits the provided manifest for issues.",
                "consumes": [
                    "text/plain",
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "AuditHandler audits the provided manifest.",
                "parameters": [
                    {
                        "description": "Manifest data to audit (either plain text or JSON format)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audit.Payload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Audit results",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/scanner.Issue"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/audit/score": {
            "post": {
                "description": "This endpoint calculates a score for the provided manifest based on the number and severity of issues detected during the audit.",
                "consumes": [
                    "text/plain",
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "ScoreHandler calculates a score for the audited manifest.",
                "parameters": [
                    {
                        "description": "Manifest data to calculate score for (either plain text or JSON format)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audit.Payload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Score calculation result",
                        "schema": {
                            "$ref": "#/definitions/audit.ScoreData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/cluster/config/file": {
            "post": {
                "description": "Uploads a KubeConfig file for cluster, with a maximum size of 2MB, and the valid file extension is \"\", \".yaml\", \".yml\", \".json\", \".kubeconfig\", \".kubeconf\".",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Upload kubeConfig file for cluster",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Upload file with field name 'file'",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the content of the uploaded KubeConfig file.",
                        "schema": {
                            "$ref": "#/definitions/cluster.UploadData"
                        }
                    },
                    "400": {
                        "description": "The uploaded file is too large or the request is invalid.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audit.Payload": {
            "type": "object",
            "properties": {
                "manifest": {
                    "description": "Manifest is the content to be audited.",
                    "type": "string"
                }
            }
        },
        "audit.ScoreData": {
            "type": "object",
            "properties": {
                "issuesTotal": {
                    "description": "IssuesTotal is the total count of all issues found during the audit.\nThis count can be used to understand the overall number of problems\nthat need to be addressed.",
                    "type": "integer"
                },
                "score": {
                    "description": "Score represents the calculated score of the audited manifest based on\nthe number and severity of issues. It provides a quantitative measure\nof the security posture of the resources in the manifest.",
                    "type": "number"
                },
                "severityStatistic": {
                    "description": "SeverityStatistic is a mapping of severity levels to their respective\nnumber of occurrences. It allows for a quick overview of the distribution\nof issues across different severity categories.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "severitySum": {
                    "description": "SeveritySum is the sum of severity scores of all issues, which can be\nused to gauge the cumulative severity of all problems found.",
                    "type": "integer"
                }
            }
        },
        "cluster.UploadData": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                }
            }
        },
        "scanner.Issue": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message provides a detailed human-readable description of the issue.",
                    "type": "string"
                },
                "scanner": {
                    "description": "Scanner is the name of the scanner that discovered the issue.",
                    "type": "string"
                },
                "severity": {
                    "description": "Severity indicates how critical the issue is, using the IssueSeverityLevel constants.",
                    "type": "integer"
                },
                "title": {
                    "description": "Title is a brief summary of the issue.",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
