definitions:
  audit.Payload:
    properties:
      manifest:
        description: Manifest is the content to be audited.
        type: string
    type: object
  audit.ScoreData:
    properties:
      issuesTotal:
        description: |-
          IssuesTotal is the total count of all issues found during the audit.
          This count can be used to understand the overall number of problems
          that need to be addressed.
        type: integer
      score:
        description: |-
          Score represents the calculated score of the audited manifest based on
          the number and severity of issues. It provides a quantitative measure
          of the security posture of the resources in the manifest.
        type: number
      severityStatistic:
        additionalProperties:
          type: integer
        description: |-
          SeverityStatistic is a mapping of severity levels to their respective
          number of occurrences. It allows for a quick overview of the distribution
          of issues across different severity categories.
        type: object
      severitySum:
        description: |-
          SeveritySum is the sum of severity scores of all issues, which can be
          used to gauge the cumulative severity of all problems found.
        type: integer
    type: object
  scanner.Issue:
    properties:
      message:
        description: Message provides a detailed human-readable description of the
          issue.
        type: string
      scanner:
        description: Scanner is the name of the scanner that discovered the issue.
        type: string
      severity:
        description: Severity indicates how critical the issue is, using the IssueSeverityLevel
          constants.
        type: integer
      title:
        description: Title is a brief summary of the issue.
        type: string
    type: object
info:
  contact: {}
paths:
  /audit:
    post:
      consumes:
      - text/plain
      - application/json
      description: This endpoint audits the provided manifest for issues.
      parameters:
      - description: Manifest data to audit (either plain text or JSON format)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/audit.Payload'
      produces:
      - application/json
      responses:
        "200":
          description: Audit results
          schema:
            items:
              $ref: '#/definitions/scanner.Issue'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "429":
          description: Too Many Requests
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: AuditHandler audits the provided manifest.
      tags:
      - audit
  /audit/score:
    post:
      consumes:
      - text/plain
      - application/json
      description: This endpoint calculates a score for the provided manifest based
        on the number and severity of issues detected during the audit.
      parameters:
      - description: Manifest data to calculate score for (either plain text or JSON
          format)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/audit.Payload'
      produces:
      - application/json
      responses:
        "200":
          description: Score calculation result
          schema:
            $ref: '#/definitions/audit.ScoreData'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "429":
          description: Too Many Requests
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: ScoreHandler calculates a score for the audited manifest.
      tags:
      - audit
swagger: "2.0"
