# Copyright The Karpor Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file contains all available configuration options
# with their default values.
# For complete .golangci.yml configuration, reference: https://golangci-lint.run/usage/configuration/#config-file

# options for analysis running
run:
  timeout: 5m
  go: '1.19'
  concurrency: 8
  allow-parallel-runners: true
  cache-dir: .cache/golangci-lint
  modules-download-mode: readonly
  max-same-issues: 50

linters:
  disable-all: true
  enable: # please keep this alphabetized
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - errorlint
    - errname
    - exportloopref
    - forbidigo
    - gosimple
    - gocritic
    - goconst
    - gofumpt
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - nolintlint
    - nilerr
    - nilnil
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - tagliatelle
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

linters-settings:
  gofumpt:
    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules: false
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      # Default: false
      use-field-name: true
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `upperSnake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`, `header`.
        json: goCamel
        yaml: goCamel
        xml: goCamel
        toml: goCamel
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    # See the https://github.com/polyfloyd/go-errorlint for caveats.
    # Default: true
    errorf: false
  govet:
    # disable buildssa analyzer to fix k8s.io/kube-aggregator issue
    disable:
      - buildssa

issues:
  exclude-dirs:
    - "api/openapispec"
    - "hack"
  exclude-files:
    - ".*\\.pb\\.go$"
    - "internal_import\\.go$"
    - ".*\\.gen\\.go$"
    - pkg/kubernetes/openapi/zz_generated.openapi.go
    - pkg/kubernetes/internalimport/internal_import.go
  exclude:
    - "G306: Expect WriteFile permissions to be 0600 or less"
    - "ST1018: string literal contains Unicode control characters, consider using escape sequences instead"
    - "ifElseChain: rewrite if-else to switch statement"
    - "S1000: should use for range instead of for { select {} }"
    - "SA4004: the surrounding loop is unconditionally terminated"
    - "copylocks: call of c\\.Post copies lock value: kusionstack\\.io/kclvm-go/pkg/spec/gpyrpc\\.Ping_Args contains google\\.golang\\.org/protobuf/internal/impl\\.MessageState contains sync\\.Mutex"
