//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Karbour Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	search "github.com/KusionStack/karbour/pkg/apis/search"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterSyncResourcesCondition)(nil), (*search.ClusterSyncResourcesCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterSyncResourcesCondition_To_search_ClusterSyncResourcesCondition(a.(*ClusterSyncResourcesCondition), b.(*search.ClusterSyncResourcesCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.ClusterSyncResourcesCondition)(nil), (*ClusterSyncResourcesCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_ClusterSyncResourcesCondition_To_v1beta1_ClusterSyncResourcesCondition(a.(*search.ClusterSyncResourcesCondition), b.(*ClusterSyncResourcesCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FieldSelector)(nil), (*search.FieldSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FieldSelector_To_search_FieldSelector(a.(*FieldSelector), b.(*search.FieldSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.FieldSelector)(nil), (*FieldSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_FieldSelector_To_v1beta1_FieldSelector(a.(*search.FieldSelector), b.(*FieldSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceSyncCondition)(nil), (*search.ResourceSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition(a.(*ResourceSyncCondition), b.(*search.ResourceSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.ResourceSyncCondition)(nil), (*ResourceSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition(a.(*search.ResourceSyncCondition), b.(*ResourceSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceSyncRule)(nil), (*search.ResourceSyncRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule(a.(*ResourceSyncRule), b.(*search.ResourceSyncRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.ResourceSyncRule)(nil), (*ResourceSyncRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule(a.(*search.ResourceSyncRule), b.(*ResourceSyncRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Selector)(nil), (*search.Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Selector_To_search_Selector(a.(*Selector), b.(*search.Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.Selector)(nil), (*Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_Selector_To_v1beta1_Selector(a.(*search.Selector), b.(*Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncClustersResources)(nil), (*search.SyncClustersResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncClustersResources_To_search_SyncClustersResources(a.(*SyncClustersResources), b.(*search.SyncClustersResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncClustersResources)(nil), (*SyncClustersResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncClustersResources_To_v1beta1_SyncClustersResources(a.(*search.SyncClustersResources), b.(*SyncClustersResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncClustersResourcesList)(nil), (*search.SyncClustersResourcesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncClustersResourcesList_To_search_SyncClustersResourcesList(a.(*SyncClustersResourcesList), b.(*search.SyncClustersResourcesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncClustersResourcesList)(nil), (*SyncClustersResourcesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncClustersResourcesList_To_v1beta1_SyncClustersResourcesList(a.(*search.SyncClustersResourcesList), b.(*SyncClustersResourcesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncClustersResourcesSpec)(nil), (*search.SyncClustersResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncClustersResourcesSpec_To_search_SyncClustersResourcesSpec(a.(*SyncClustersResourcesSpec), b.(*search.SyncClustersResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncClustersResourcesSpec)(nil), (*SyncClustersResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncClustersResourcesSpec_To_v1beta1_SyncClustersResourcesSpec(a.(*search.SyncClustersResourcesSpec), b.(*SyncClustersResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncClustersResourcesStatus)(nil), (*search.SyncClustersResourcesStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncClustersResourcesStatus_To_search_SyncClustersResourcesStatus(a.(*SyncClustersResourcesStatus), b.(*search.SyncClustersResourcesStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncClustersResourcesStatus)(nil), (*SyncClustersResourcesStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncClustersResourcesStatus_To_v1beta1_SyncClustersResourcesStatus(a.(*search.SyncClustersResourcesStatus), b.(*SyncClustersResourcesStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncResources)(nil), (*search.SyncResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncResources_To_search_SyncResources(a.(*SyncResources), b.(*search.SyncResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncResources)(nil), (*SyncResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncResources_To_v1beta1_SyncResources(a.(*search.SyncResources), b.(*SyncResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncResourcesList)(nil), (*search.SyncResourcesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncResourcesList_To_search_SyncResourcesList(a.(*SyncResourcesList), b.(*search.SyncResourcesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncResourcesList)(nil), (*SyncResourcesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncResourcesList_To_v1beta1_SyncResourcesList(a.(*search.SyncResourcesList), b.(*SyncResourcesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncResourcesSpec)(nil), (*search.SyncResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(a.(*SyncResourcesSpec), b.(*search.SyncResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncResourcesSpec)(nil), (*SyncResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(a.(*search.SyncResourcesSpec), b.(*SyncResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TransformRule)(nil), (*search.TransformRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TransformRule_To_search_TransformRule(a.(*TransformRule), b.(*search.TransformRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.TransformRule)(nil), (*TransformRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_TransformRule_To_v1beta1_TransformRule(a.(*search.TransformRule), b.(*TransformRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TransformRuleList)(nil), (*search.TransformRuleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TransformRuleList_To_search_TransformRuleList(a.(*TransformRuleList), b.(*search.TransformRuleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.TransformRuleList)(nil), (*TransformRuleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_TransformRuleList_To_v1beta1_TransformRuleList(a.(*search.TransformRuleList), b.(*TransformRuleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TransformRuleSpec)(nil), (*search.TransformRuleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(a.(*TransformRuleSpec), b.(*search.TransformRuleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.TransformRuleSpec)(nil), (*TransformRuleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(a.(*search.TransformRuleSpec), b.(*TransformRuleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniResource)(nil), (*search.UniResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniResource_To_search_UniResource(a.(*UniResource), b.(*search.UniResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniResource)(nil), (*UniResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniResource_To_v1beta1_UniResource(a.(*search.UniResource), b.(*UniResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniResourceList)(nil), (*search.UniResourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniResourceList_To_search_UniResourceList(a.(*UniResourceList), b.(*search.UniResourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniResourceList)(nil), (*UniResourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniResourceList_To_v1beta1_UniResourceList(a.(*search.UniResourceList), b.(*UniResourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniResourceTopology)(nil), (*search.UniResourceTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniResourceTopology_To_search_UniResourceTopology(a.(*UniResourceTopology), b.(*search.UniResourceTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniResourceTopology)(nil), (*UniResourceTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniResourceTopology_To_v1beta1_UniResourceTopology(a.(*search.UniResourceTopology), b.(*UniResourceTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniResourceTopologyList)(nil), (*search.UniResourceTopologyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniResourceTopologyList_To_search_UniResourceTopologyList(a.(*UniResourceTopologyList), b.(*search.UniResourceTopologyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniResourceTopologyList)(nil), (*UniResourceTopologyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniResourceTopologyList_To_v1beta1_UniResourceTopologyList(a.(*search.UniResourceTopologyList), b.(*UniResourceTopologyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniResourceYAML)(nil), (*search.UniResourceYAML)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniResourceYAML_To_search_UniResourceYAML(a.(*UniResourceYAML), b.(*search.UniResourceYAML), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniResourceYAML)(nil), (*UniResourceYAML)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniResourceYAML_To_v1beta1_UniResourceYAML(a.(*search.UniResourceYAML), b.(*UniResourceYAML), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniResourceYAMLList)(nil), (*search.UniResourceYAMLList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniResourceYAMLList_To_search_UniResourceYAMLList(a.(*UniResourceYAMLList), b.(*search.UniResourceYAMLList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniResourceYAMLList)(nil), (*UniResourceYAMLList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniResourceYAMLList_To_v1beta1_UniResourceYAMLList(a.(*search.UniResourceYAMLList), b.(*UniResourceYAMLList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniresourceNode)(nil), (*search.UniresourceNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniresourceNode_To_search_UniresourceNode(a.(*UniresourceNode), b.(*search.UniresourceNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniresourceNode)(nil), (*UniresourceNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniresourceNode_To_v1beta1_UniresourceNode(a.(*search.UniresourceNode), b.(*UniresourceNode), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_ClusterSyncResourcesCondition_To_search_ClusterSyncResourcesCondition(in *ClusterSyncResourcesCondition, out *search.ClusterSyncResourcesCondition, s conversion.Scope) error {
	out.Cluster = in.Cluster
	out.Status = in.Status
	out.Resources = *(*[]search.ResourceSyncCondition)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1beta1_ClusterSyncResourcesCondition_To_search_ClusterSyncResourcesCondition is an autogenerated conversion function.
func Convert_v1beta1_ClusterSyncResourcesCondition_To_search_ClusterSyncResourcesCondition(in *ClusterSyncResourcesCondition, out *search.ClusterSyncResourcesCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterSyncResourcesCondition_To_search_ClusterSyncResourcesCondition(in, out, s)
}

func autoConvert_search_ClusterSyncResourcesCondition_To_v1beta1_ClusterSyncResourcesCondition(in *search.ClusterSyncResourcesCondition, out *ClusterSyncResourcesCondition, s conversion.Scope) error {
	out.Cluster = in.Cluster
	out.Status = in.Status
	out.Resources = *(*[]ResourceSyncCondition)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_search_ClusterSyncResourcesCondition_To_v1beta1_ClusterSyncResourcesCondition is an autogenerated conversion function.
func Convert_search_ClusterSyncResourcesCondition_To_v1beta1_ClusterSyncResourcesCondition(in *search.ClusterSyncResourcesCondition, out *ClusterSyncResourcesCondition, s conversion.Scope) error {
	return autoConvert_search_ClusterSyncResourcesCondition_To_v1beta1_ClusterSyncResourcesCondition(in, out, s)
}

func autoConvert_v1beta1_FieldSelector_To_search_FieldSelector(in *FieldSelector, out *search.FieldSelector, s conversion.Scope) error {
	out.MatchFields = *(*map[string]string)(unsafe.Pointer(&in.MatchFields))
	out.SeverSupported = in.SeverSupported
	return nil
}

// Convert_v1beta1_FieldSelector_To_search_FieldSelector is an autogenerated conversion function.
func Convert_v1beta1_FieldSelector_To_search_FieldSelector(in *FieldSelector, out *search.FieldSelector, s conversion.Scope) error {
	return autoConvert_v1beta1_FieldSelector_To_search_FieldSelector(in, out, s)
}

func autoConvert_search_FieldSelector_To_v1beta1_FieldSelector(in *search.FieldSelector, out *FieldSelector, s conversion.Scope) error {
	out.MatchFields = *(*map[string]string)(unsafe.Pointer(&in.MatchFields))
	out.SeverSupported = in.SeverSupported
	return nil
}

// Convert_search_FieldSelector_To_v1beta1_FieldSelector is an autogenerated conversion function.
func Convert_search_FieldSelector_To_v1beta1_FieldSelector(in *search.FieldSelector, out *FieldSelector, s conversion.Scope) error {
	return autoConvert_search_FieldSelector_To_v1beta1_FieldSelector(in, out, s)
}

func autoConvert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition(in *ResourceSyncCondition, out *search.ResourceSyncCondition, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Status = in.Status
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition is an autogenerated conversion function.
func Convert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition(in *ResourceSyncCondition, out *search.ResourceSyncCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition(in, out, s)
}

func autoConvert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition(in *search.ResourceSyncCondition, out *ResourceSyncCondition, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Status = in.Status
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition is an autogenerated conversion function.
func Convert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition(in *search.ResourceSyncCondition, out *ResourceSyncCondition, s conversion.Scope) error {
	return autoConvert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition(in, out, s)
}

func autoConvert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule(in *ResourceSyncRule, out *search.ResourceSyncRule, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Selectors = *(*[]search.Selector)(unsafe.Pointer(&in.Selectors))
	if err := Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(&in.Transform, &out.Transform, s); err != nil {
		return err
	}
	out.TransformRefName = in.TransformRefName
	return nil
}

// Convert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule is an autogenerated conversion function.
func Convert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule(in *ResourceSyncRule, out *search.ResourceSyncRule, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule(in, out, s)
}

func autoConvert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule(in *search.ResourceSyncRule, out *ResourceSyncRule, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Selectors = *(*[]Selector)(unsafe.Pointer(&in.Selectors))
	if err := Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(&in.Transform, &out.Transform, s); err != nil {
		return err
	}
	out.TransformRefName = in.TransformRefName
	return nil
}

// Convert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule is an autogenerated conversion function.
func Convert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule(in *search.ResourceSyncRule, out *ResourceSyncRule, s conversion.Scope) error {
	return autoConvert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule(in, out, s)
}

func autoConvert_v1beta1_Selector_To_search_Selector(in *Selector, out *search.Selector, s conversion.Scope) error {
	out.LabelSelector = (*v1.LabelSelector)(unsafe.Pointer(in.LabelSelector))
	out.FieldSelector = (*search.FieldSelector)(unsafe.Pointer(in.FieldSelector))
	return nil
}

// Convert_v1beta1_Selector_To_search_Selector is an autogenerated conversion function.
func Convert_v1beta1_Selector_To_search_Selector(in *Selector, out *search.Selector, s conversion.Scope) error {
	return autoConvert_v1beta1_Selector_To_search_Selector(in, out, s)
}

func autoConvert_search_Selector_To_v1beta1_Selector(in *search.Selector, out *Selector, s conversion.Scope) error {
	out.LabelSelector = (*v1.LabelSelector)(unsafe.Pointer(in.LabelSelector))
	out.FieldSelector = (*FieldSelector)(unsafe.Pointer(in.FieldSelector))
	return nil
}

// Convert_search_Selector_To_v1beta1_Selector is an autogenerated conversion function.
func Convert_search_Selector_To_v1beta1_Selector(in *search.Selector, out *Selector, s conversion.Scope) error {
	return autoConvert_search_Selector_To_v1beta1_Selector(in, out, s)
}

func autoConvert_v1beta1_SyncClustersResources_To_search_SyncClustersResources(in *SyncClustersResources, out *search.SyncClustersResources, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SyncClustersResourcesSpec_To_search_SyncClustersResourcesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SyncClustersResourcesStatus_To_search_SyncClustersResourcesStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SyncClustersResources_To_search_SyncClustersResources is an autogenerated conversion function.
func Convert_v1beta1_SyncClustersResources_To_search_SyncClustersResources(in *SyncClustersResources, out *search.SyncClustersResources, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncClustersResources_To_search_SyncClustersResources(in, out, s)
}

func autoConvert_search_SyncClustersResources_To_v1beta1_SyncClustersResources(in *search.SyncClustersResources, out *SyncClustersResources, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_search_SyncClustersResourcesSpec_To_v1beta1_SyncClustersResourcesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_search_SyncClustersResourcesStatus_To_v1beta1_SyncClustersResourcesStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_search_SyncClustersResources_To_v1beta1_SyncClustersResources is an autogenerated conversion function.
func Convert_search_SyncClustersResources_To_v1beta1_SyncClustersResources(in *search.SyncClustersResources, out *SyncClustersResources, s conversion.Scope) error {
	return autoConvert_search_SyncClustersResources_To_v1beta1_SyncClustersResources(in, out, s)
}

func autoConvert_v1beta1_SyncClustersResourcesList_To_search_SyncClustersResourcesList(in *SyncClustersResourcesList, out *search.SyncClustersResourcesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]search.SyncClustersResources)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_SyncClustersResourcesList_To_search_SyncClustersResourcesList is an autogenerated conversion function.
func Convert_v1beta1_SyncClustersResourcesList_To_search_SyncClustersResourcesList(in *SyncClustersResourcesList, out *search.SyncClustersResourcesList, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncClustersResourcesList_To_search_SyncClustersResourcesList(in, out, s)
}

func autoConvert_search_SyncClustersResourcesList_To_v1beta1_SyncClustersResourcesList(in *search.SyncClustersResourcesList, out *SyncClustersResourcesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SyncClustersResources)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_search_SyncClustersResourcesList_To_v1beta1_SyncClustersResourcesList is an autogenerated conversion function.
func Convert_search_SyncClustersResourcesList_To_v1beta1_SyncClustersResourcesList(in *search.SyncClustersResourcesList, out *SyncClustersResourcesList, s conversion.Scope) error {
	return autoConvert_search_SyncClustersResourcesList_To_v1beta1_SyncClustersResourcesList(in, out, s)
}

func autoConvert_v1beta1_SyncClustersResourcesSpec_To_search_SyncClustersResourcesSpec(in *SyncClustersResourcesSpec, out *search.SyncClustersResourcesSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_Selector_To_search_Selector(&in.ClusterSelector, &out.ClusterSelector, s); err != nil {
		return err
	}
	out.ClusterNames = *(*[]string)(unsafe.Pointer(&in.ClusterNames))
	out.SyncResources = *(*[]search.ResourceSyncRule)(unsafe.Pointer(&in.SyncResources))
	out.SyncResourcesRefName = in.SyncResourcesRefName
	return nil
}

// Convert_v1beta1_SyncClustersResourcesSpec_To_search_SyncClustersResourcesSpec is an autogenerated conversion function.
func Convert_v1beta1_SyncClustersResourcesSpec_To_search_SyncClustersResourcesSpec(in *SyncClustersResourcesSpec, out *search.SyncClustersResourcesSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncClustersResourcesSpec_To_search_SyncClustersResourcesSpec(in, out, s)
}

func autoConvert_search_SyncClustersResourcesSpec_To_v1beta1_SyncClustersResourcesSpec(in *search.SyncClustersResourcesSpec, out *SyncClustersResourcesSpec, s conversion.Scope) error {
	if err := Convert_search_Selector_To_v1beta1_Selector(&in.ClusterSelector, &out.ClusterSelector, s); err != nil {
		return err
	}
	out.ClusterNames = *(*[]string)(unsafe.Pointer(&in.ClusterNames))
	out.SyncResources = *(*[]ResourceSyncRule)(unsafe.Pointer(&in.SyncResources))
	out.SyncResourcesRefName = in.SyncResourcesRefName
	return nil
}

// Convert_search_SyncClustersResourcesSpec_To_v1beta1_SyncClustersResourcesSpec is an autogenerated conversion function.
func Convert_search_SyncClustersResourcesSpec_To_v1beta1_SyncClustersResourcesSpec(in *search.SyncClustersResourcesSpec, out *SyncClustersResourcesSpec, s conversion.Scope) error {
	return autoConvert_search_SyncClustersResourcesSpec_To_v1beta1_SyncClustersResourcesSpec(in, out, s)
}

func autoConvert_v1beta1_SyncClustersResourcesStatus_To_search_SyncClustersResourcesStatus(in *SyncClustersResourcesStatus, out *search.SyncClustersResourcesStatus, s conversion.Scope) error {
	out.Clusters = *(*[]search.ClusterSyncResourcesCondition)(unsafe.Pointer(&in.Clusters))
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_v1beta1_SyncClustersResourcesStatus_To_search_SyncClustersResourcesStatus is an autogenerated conversion function.
func Convert_v1beta1_SyncClustersResourcesStatus_To_search_SyncClustersResourcesStatus(in *SyncClustersResourcesStatus, out *search.SyncClustersResourcesStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncClustersResourcesStatus_To_search_SyncClustersResourcesStatus(in, out, s)
}

func autoConvert_search_SyncClustersResourcesStatus_To_v1beta1_SyncClustersResourcesStatus(in *search.SyncClustersResourcesStatus, out *SyncClustersResourcesStatus, s conversion.Scope) error {
	out.Clusters = *(*[]ClusterSyncResourcesCondition)(unsafe.Pointer(&in.Clusters))
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_search_SyncClustersResourcesStatus_To_v1beta1_SyncClustersResourcesStatus is an autogenerated conversion function.
func Convert_search_SyncClustersResourcesStatus_To_v1beta1_SyncClustersResourcesStatus(in *search.SyncClustersResourcesStatus, out *SyncClustersResourcesStatus, s conversion.Scope) error {
	return autoConvert_search_SyncClustersResourcesStatus_To_v1beta1_SyncClustersResourcesStatus(in, out, s)
}

func autoConvert_v1beta1_SyncResources_To_search_SyncResources(in *SyncResources, out *search.SyncResources, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SyncResources_To_search_SyncResources is an autogenerated conversion function.
func Convert_v1beta1_SyncResources_To_search_SyncResources(in *SyncResources, out *search.SyncResources, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncResources_To_search_SyncResources(in, out, s)
}

func autoConvert_search_SyncResources_To_v1beta1_SyncResources(in *search.SyncResources, out *SyncResources, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_search_SyncResources_To_v1beta1_SyncResources is an autogenerated conversion function.
func Convert_search_SyncResources_To_v1beta1_SyncResources(in *search.SyncResources, out *SyncResources, s conversion.Scope) error {
	return autoConvert_search_SyncResources_To_v1beta1_SyncResources(in, out, s)
}

func autoConvert_v1beta1_SyncResourcesList_To_search_SyncResourcesList(in *SyncResourcesList, out *search.SyncResourcesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]search.SyncResources)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_SyncResourcesList_To_search_SyncResourcesList is an autogenerated conversion function.
func Convert_v1beta1_SyncResourcesList_To_search_SyncResourcesList(in *SyncResourcesList, out *search.SyncResourcesList, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncResourcesList_To_search_SyncResourcesList(in, out, s)
}

func autoConvert_search_SyncResourcesList_To_v1beta1_SyncResourcesList(in *search.SyncResourcesList, out *SyncResourcesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SyncResources)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_search_SyncResourcesList_To_v1beta1_SyncResourcesList is an autogenerated conversion function.
func Convert_search_SyncResourcesList_To_v1beta1_SyncResourcesList(in *search.SyncResourcesList, out *SyncResourcesList, s conversion.Scope) error {
	return autoConvert_search_SyncResourcesList_To_v1beta1_SyncResourcesList(in, out, s)
}

func autoConvert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(in *SyncResourcesSpec, out *search.SyncResourcesSpec, s conversion.Scope) error {
	out.SyncResources = *(*[]search.ResourceSyncRule)(unsafe.Pointer(&in.SyncResources))
	return nil
}

// Convert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec is an autogenerated conversion function.
func Convert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(in *SyncResourcesSpec, out *search.SyncResourcesSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(in, out, s)
}

func autoConvert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(in *search.SyncResourcesSpec, out *SyncResourcesSpec, s conversion.Scope) error {
	out.SyncResources = *(*[]ResourceSyncRule)(unsafe.Pointer(&in.SyncResources))
	return nil
}

// Convert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec is an autogenerated conversion function.
func Convert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(in *search.SyncResourcesSpec, out *SyncResourcesSpec, s conversion.Scope) error {
	return autoConvert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(in, out, s)
}

func autoConvert_v1beta1_TransformRule_To_search_TransformRule(in *TransformRule, out *search.TransformRule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TransformRule_To_search_TransformRule is an autogenerated conversion function.
func Convert_v1beta1_TransformRule_To_search_TransformRule(in *TransformRule, out *search.TransformRule, s conversion.Scope) error {
	return autoConvert_v1beta1_TransformRule_To_search_TransformRule(in, out, s)
}

func autoConvert_search_TransformRule_To_v1beta1_TransformRule(in *search.TransformRule, out *TransformRule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_search_TransformRule_To_v1beta1_TransformRule is an autogenerated conversion function.
func Convert_search_TransformRule_To_v1beta1_TransformRule(in *search.TransformRule, out *TransformRule, s conversion.Scope) error {
	return autoConvert_search_TransformRule_To_v1beta1_TransformRule(in, out, s)
}

func autoConvert_v1beta1_TransformRuleList_To_search_TransformRuleList(in *TransformRuleList, out *search.TransformRuleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]search.TransformRule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_TransformRuleList_To_search_TransformRuleList is an autogenerated conversion function.
func Convert_v1beta1_TransformRuleList_To_search_TransformRuleList(in *TransformRuleList, out *search.TransformRuleList, s conversion.Scope) error {
	return autoConvert_v1beta1_TransformRuleList_To_search_TransformRuleList(in, out, s)
}

func autoConvert_search_TransformRuleList_To_v1beta1_TransformRuleList(in *search.TransformRuleList, out *TransformRuleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]TransformRule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_search_TransformRuleList_To_v1beta1_TransformRuleList is an autogenerated conversion function.
func Convert_search_TransformRuleList_To_v1beta1_TransformRuleList(in *search.TransformRuleList, out *TransformRuleList, s conversion.Scope) error {
	return autoConvert_search_TransformRuleList_To_v1beta1_TransformRuleList(in, out, s)
}

func autoConvert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(in *TransformRuleSpec, out *search.TransformRuleSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.ValueTemplate = in.ValueTemplate
	return nil
}

// Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec is an autogenerated conversion function.
func Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(in *TransformRuleSpec, out *search.TransformRuleSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(in, out, s)
}

func autoConvert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(in *search.TransformRuleSpec, out *TransformRuleSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.ValueTemplate = in.ValueTemplate
	return nil
}

// Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec is an autogenerated conversion function.
func Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(in *search.TransformRuleSpec, out *TransformRuleSpec, s conversion.Scope) error {
	return autoConvert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(in, out, s)
}

func autoConvert_v1beta1_UniResource_To_search_UniResource(in *UniResource, out *search.UniResource, s conversion.Scope) error {
	if err := Convert_v1beta1_UniResourceTopology_To_search_UniResourceTopology(&in.Topology, &out.Topology, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_UniResourceYAML_To_search_UniResourceYAML(&in.YAML, &out.YAML, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_UniResource_To_search_UniResource is an autogenerated conversion function.
func Convert_v1beta1_UniResource_To_search_UniResource(in *UniResource, out *search.UniResource, s conversion.Scope) error {
	return autoConvert_v1beta1_UniResource_To_search_UniResource(in, out, s)
}

func autoConvert_search_UniResource_To_v1beta1_UniResource(in *search.UniResource, out *UniResource, s conversion.Scope) error {
	if err := Convert_search_UniResourceTopology_To_v1beta1_UniResourceTopology(&in.Topology, &out.Topology, s); err != nil {
		return err
	}
	if err := Convert_search_UniResourceYAML_To_v1beta1_UniResourceYAML(&in.YAML, &out.YAML, s); err != nil {
		return err
	}
	return nil
}

// Convert_search_UniResource_To_v1beta1_UniResource is an autogenerated conversion function.
func Convert_search_UniResource_To_v1beta1_UniResource(in *search.UniResource, out *UniResource, s conversion.Scope) error {
	return autoConvert_search_UniResource_To_v1beta1_UniResource(in, out, s)
}

func autoConvert_v1beta1_UniResourceList_To_search_UniResourceList(in *UniResourceList, out *search.UniResourceList, s conversion.Scope) error {
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]runtime.Object, len(*in))
		for i := range *in {
			if err := runtime.Convert_runtime_RawExtension_To_runtime_Object(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_UniResourceList_To_search_UniResourceList is an autogenerated conversion function.
func Convert_v1beta1_UniResourceList_To_search_UniResourceList(in *UniResourceList, out *search.UniResourceList, s conversion.Scope) error {
	return autoConvert_v1beta1_UniResourceList_To_search_UniResourceList(in, out, s)
}

func autoConvert_search_UniResourceList_To_v1beta1_UniResourceList(in *search.UniResourceList, out *UniResourceList, s conversion.Scope) error {
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			if err := runtime.Convert_runtime_Object_To_runtime_RawExtension(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_search_UniResourceList_To_v1beta1_UniResourceList is an autogenerated conversion function.
func Convert_search_UniResourceList_To_v1beta1_UniResourceList(in *search.UniResourceList, out *UniResourceList, s conversion.Scope) error {
	return autoConvert_search_UniResourceList_To_v1beta1_UniResourceList(in, out, s)
}

func autoConvert_v1beta1_UniResourceTopology_To_search_UniResourceTopology(in *UniResourceTopology, out *search.UniResourceTopology, s conversion.Scope) error {
	out.Graph = *(*map[string]search.UniresourceNode)(unsafe.Pointer(&in.Graph))
	return nil
}

// Convert_v1beta1_UniResourceTopology_To_search_UniResourceTopology is an autogenerated conversion function.
func Convert_v1beta1_UniResourceTopology_To_search_UniResourceTopology(in *UniResourceTopology, out *search.UniResourceTopology, s conversion.Scope) error {
	return autoConvert_v1beta1_UniResourceTopology_To_search_UniResourceTopology(in, out, s)
}

func autoConvert_search_UniResourceTopology_To_v1beta1_UniResourceTopology(in *search.UniResourceTopology, out *UniResourceTopology, s conversion.Scope) error {
	out.Graph = *(*map[string]UniresourceNode)(unsafe.Pointer(&in.Graph))
	return nil
}

// Convert_search_UniResourceTopology_To_v1beta1_UniResourceTopology is an autogenerated conversion function.
func Convert_search_UniResourceTopology_To_v1beta1_UniResourceTopology(in *search.UniResourceTopology, out *UniResourceTopology, s conversion.Scope) error {
	return autoConvert_search_UniResourceTopology_To_v1beta1_UniResourceTopology(in, out, s)
}

func autoConvert_v1beta1_UniResourceTopologyList_To_search_UniResourceTopologyList(in *UniResourceTopologyList, out *search.UniResourceTopologyList, s conversion.Scope) error {
	out.Items = *(*[]search.UniResourceTopology)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_UniResourceTopologyList_To_search_UniResourceTopologyList is an autogenerated conversion function.
func Convert_v1beta1_UniResourceTopologyList_To_search_UniResourceTopologyList(in *UniResourceTopologyList, out *search.UniResourceTopologyList, s conversion.Scope) error {
	return autoConvert_v1beta1_UniResourceTopologyList_To_search_UniResourceTopologyList(in, out, s)
}

func autoConvert_search_UniResourceTopologyList_To_v1beta1_UniResourceTopologyList(in *search.UniResourceTopologyList, out *UniResourceTopologyList, s conversion.Scope) error {
	out.Items = *(*[]UniResourceTopology)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_search_UniResourceTopologyList_To_v1beta1_UniResourceTopologyList is an autogenerated conversion function.
func Convert_search_UniResourceTopologyList_To_v1beta1_UniResourceTopologyList(in *search.UniResourceTopologyList, out *UniResourceTopologyList, s conversion.Scope) error {
	return autoConvert_search_UniResourceTopologyList_To_v1beta1_UniResourceTopologyList(in, out, s)
}

func autoConvert_v1beta1_UniResourceYAML_To_search_UniResourceYAML(in *UniResourceYAML, out *search.UniResourceYAML, s conversion.Scope) error {
	out.YAMLString = in.YAMLString
	return nil
}

// Convert_v1beta1_UniResourceYAML_To_search_UniResourceYAML is an autogenerated conversion function.
func Convert_v1beta1_UniResourceYAML_To_search_UniResourceYAML(in *UniResourceYAML, out *search.UniResourceYAML, s conversion.Scope) error {
	return autoConvert_v1beta1_UniResourceYAML_To_search_UniResourceYAML(in, out, s)
}

func autoConvert_search_UniResourceYAML_To_v1beta1_UniResourceYAML(in *search.UniResourceYAML, out *UniResourceYAML, s conversion.Scope) error {
	out.YAMLString = in.YAMLString
	return nil
}

// Convert_search_UniResourceYAML_To_v1beta1_UniResourceYAML is an autogenerated conversion function.
func Convert_search_UniResourceYAML_To_v1beta1_UniResourceYAML(in *search.UniResourceYAML, out *UniResourceYAML, s conversion.Scope) error {
	return autoConvert_search_UniResourceYAML_To_v1beta1_UniResourceYAML(in, out, s)
}

func autoConvert_v1beta1_UniResourceYAMLList_To_search_UniResourceYAMLList(in *UniResourceYAMLList, out *search.UniResourceYAMLList, s conversion.Scope) error {
	out.Items = *(*[]search.UniResourceYAML)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_UniResourceYAMLList_To_search_UniResourceYAMLList is an autogenerated conversion function.
func Convert_v1beta1_UniResourceYAMLList_To_search_UniResourceYAMLList(in *UniResourceYAMLList, out *search.UniResourceYAMLList, s conversion.Scope) error {
	return autoConvert_v1beta1_UniResourceYAMLList_To_search_UniResourceYAMLList(in, out, s)
}

func autoConvert_search_UniResourceYAMLList_To_v1beta1_UniResourceYAMLList(in *search.UniResourceYAMLList, out *UniResourceYAMLList, s conversion.Scope) error {
	out.Items = *(*[]UniResourceYAML)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_search_UniResourceYAMLList_To_v1beta1_UniResourceYAMLList is an autogenerated conversion function.
func Convert_search_UniResourceYAMLList_To_v1beta1_UniResourceYAMLList(in *search.UniResourceYAMLList, out *UniResourceYAMLList, s conversion.Scope) error {
	return autoConvert_search_UniResourceYAMLList_To_v1beta1_UniResourceYAMLList(in, out, s)
}

func autoConvert_v1beta1_UniresourceNode_To_search_UniresourceNode(in *UniresourceNode, out *search.UniresourceNode, s conversion.Scope) error {
	out.Identifier = in.Identifier
	out.Parents = *(*[]string)(unsafe.Pointer(&in.Parents))
	out.Children = *(*[]string)(unsafe.Pointer(&in.Children))
	return nil
}

// Convert_v1beta1_UniresourceNode_To_search_UniresourceNode is an autogenerated conversion function.
func Convert_v1beta1_UniresourceNode_To_search_UniresourceNode(in *UniresourceNode, out *search.UniresourceNode, s conversion.Scope) error {
	return autoConvert_v1beta1_UniresourceNode_To_search_UniresourceNode(in, out, s)
}

func autoConvert_search_UniresourceNode_To_v1beta1_UniresourceNode(in *search.UniresourceNode, out *UniresourceNode, s conversion.Scope) error {
	out.Identifier = in.Identifier
	out.Parents = *(*[]string)(unsafe.Pointer(&in.Parents))
	out.Children = *(*[]string)(unsafe.Pointer(&in.Children))
	return nil
}

// Convert_search_UniresourceNode_To_v1beta1_UniresourceNode is an autogenerated conversion function.
func Convert_search_UniresourceNode_To_v1beta1_UniresourceNode(in *search.UniresourceNode, out *UniresourceNode, s conversion.Scope) error {
	return autoConvert_search_UniresourceNode_To_v1beta1_UniresourceNode(in, out, s)
}
