//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Karbour Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	search "github.com/KusionStack/karbour/pkg/apis/search"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Example)(nil), (*search.Example)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Example_To_search_Example(a.(*Example), b.(*search.Example), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.Example)(nil), (*Example)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_Example_To_v1beta1_Example(a.(*search.Example), b.(*Example), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Example_To_search_Example(in *Example, out *search.Example, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1beta1_Example_To_search_Example is an autogenerated conversion function.
func Convert_v1beta1_Example_To_search_Example(in *Example, out *search.Example, s conversion.Scope) error {
	return autoConvert_v1beta1_Example_To_search_Example(in, out, s)
}

func autoConvert_search_Example_To_v1beta1_Example(in *search.Example, out *Example, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_search_Example_To_v1beta1_Example is an autogenerated conversion function.
func Convert_search_Example_To_v1beta1_Example(in *search.Example, out *Example, s conversion.Scope) error {
	return autoConvert_search_Example_To_v1beta1_Example(in, out, s)
}
