//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Karbour Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	search "github.com/KusionStack/karbour/pkg/apis/search"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterResourcesSyncCondition)(nil), (*search.ClusterResourcesSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterResourcesSyncCondition_To_search_ClusterResourcesSyncCondition(a.(*ClusterResourcesSyncCondition), b.(*search.ClusterResourcesSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.ClusterResourcesSyncCondition)(nil), (*ClusterResourcesSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_ClusterResourcesSyncCondition_To_v1beta1_ClusterResourcesSyncCondition(a.(*search.ClusterResourcesSyncCondition), b.(*ClusterResourcesSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FieldSelector)(nil), (*search.FieldSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FieldSelector_To_search_FieldSelector(a.(*FieldSelector), b.(*search.FieldSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.FieldSelector)(nil), (*FieldSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_FieldSelector_To_v1beta1_FieldSelector(a.(*search.FieldSelector), b.(*FieldSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceSyncCondition)(nil), (*search.ResourceSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition(a.(*ResourceSyncCondition), b.(*search.ResourceSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.ResourceSyncCondition)(nil), (*ResourceSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition(a.(*search.ResourceSyncCondition), b.(*ResourceSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceSyncRule)(nil), (*search.ResourceSyncRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule(a.(*ResourceSyncRule), b.(*search.ResourceSyncRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.ResourceSyncRule)(nil), (*ResourceSyncRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule(a.(*search.ResourceSyncRule), b.(*ResourceSyncRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Selector)(nil), (*search.Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Selector_To_search_Selector(a.(*Selector), b.(*search.Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.Selector)(nil), (*Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_Selector_To_v1beta1_Selector(a.(*search.Selector), b.(*Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncRegistry)(nil), (*search.SyncRegistry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncRegistry_To_search_SyncRegistry(a.(*SyncRegistry), b.(*search.SyncRegistry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncRegistry)(nil), (*SyncRegistry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncRegistry_To_v1beta1_SyncRegistry(a.(*search.SyncRegistry), b.(*SyncRegistry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncRegistryList)(nil), (*search.SyncRegistryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncRegistryList_To_search_SyncRegistryList(a.(*SyncRegistryList), b.(*search.SyncRegistryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncRegistryList)(nil), (*SyncRegistryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncRegistryList_To_v1beta1_SyncRegistryList(a.(*search.SyncRegistryList), b.(*SyncRegistryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncRegistrySpec)(nil), (*search.SyncRegistrySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncRegistrySpec_To_search_SyncRegistrySpec(a.(*SyncRegistrySpec), b.(*search.SyncRegistrySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncRegistrySpec)(nil), (*SyncRegistrySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncRegistrySpec_To_v1beta1_SyncRegistrySpec(a.(*search.SyncRegistrySpec), b.(*SyncRegistrySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncRegistryStatus)(nil), (*search.SyncRegistryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncRegistryStatus_To_search_SyncRegistryStatus(a.(*SyncRegistryStatus), b.(*search.SyncRegistryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncRegistryStatus)(nil), (*SyncRegistryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncRegistryStatus_To_v1beta1_SyncRegistryStatus(a.(*search.SyncRegistryStatus), b.(*SyncRegistryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncResources)(nil), (*search.SyncResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncResources_To_search_SyncResources(a.(*SyncResources), b.(*search.SyncResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncResources)(nil), (*SyncResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncResources_To_v1beta1_SyncResources(a.(*search.SyncResources), b.(*SyncResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncResourcesList)(nil), (*search.SyncResourcesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncResourcesList_To_search_SyncResourcesList(a.(*SyncResourcesList), b.(*search.SyncResourcesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncResourcesList)(nil), (*SyncResourcesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncResourcesList_To_v1beta1_SyncResourcesList(a.(*search.SyncResourcesList), b.(*SyncResourcesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncResourcesSpec)(nil), (*search.SyncResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(a.(*SyncResourcesSpec), b.(*search.SyncResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.SyncResourcesSpec)(nil), (*SyncResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(a.(*search.SyncResourcesSpec), b.(*SyncResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TransformRule)(nil), (*search.TransformRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TransformRule_To_search_TransformRule(a.(*TransformRule), b.(*search.TransformRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.TransformRule)(nil), (*TransformRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_TransformRule_To_v1beta1_TransformRule(a.(*search.TransformRule), b.(*TransformRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TransformRuleList)(nil), (*search.TransformRuleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TransformRuleList_To_search_TransformRuleList(a.(*TransformRuleList), b.(*search.TransformRuleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.TransformRuleList)(nil), (*TransformRuleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_TransformRuleList_To_v1beta1_TransformRuleList(a.(*search.TransformRuleList), b.(*TransformRuleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TransformRuleSpec)(nil), (*search.TransformRuleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(a.(*TransformRuleSpec), b.(*search.TransformRuleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.TransformRuleSpec)(nil), (*TransformRuleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(a.(*search.TransformRuleSpec), b.(*TransformRuleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniResource)(nil), (*search.UniResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniResource_To_search_UniResource(a.(*UniResource), b.(*search.UniResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniResource)(nil), (*UniResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniResource_To_v1beta1_UniResource(a.(*search.UniResource), b.(*UniResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UniResourceList)(nil), (*search.UniResourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UniResourceList_To_search_UniResourceList(a.(*UniResourceList), b.(*search.UniResourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*search.UniResourceList)(nil), (*UniResourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_search_UniResourceList_To_v1beta1_UniResourceList(a.(*search.UniResourceList), b.(*UniResourceList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_ClusterResourcesSyncCondition_To_search_ClusterResourcesSyncCondition(in *ClusterResourcesSyncCondition, out *search.ClusterResourcesSyncCondition, s conversion.Scope) error {
	out.Cluster = in.Cluster
	out.Status = in.Status
	out.Resources = *(*[]search.ResourceSyncCondition)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1beta1_ClusterResourcesSyncCondition_To_search_ClusterResourcesSyncCondition is an autogenerated conversion function.
func Convert_v1beta1_ClusterResourcesSyncCondition_To_search_ClusterResourcesSyncCondition(in *ClusterResourcesSyncCondition, out *search.ClusterResourcesSyncCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterResourcesSyncCondition_To_search_ClusterResourcesSyncCondition(in, out, s)
}

func autoConvert_search_ClusterResourcesSyncCondition_To_v1beta1_ClusterResourcesSyncCondition(in *search.ClusterResourcesSyncCondition, out *ClusterResourcesSyncCondition, s conversion.Scope) error {
	out.Cluster = in.Cluster
	out.Status = in.Status
	out.Resources = *(*[]ResourceSyncCondition)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_search_ClusterResourcesSyncCondition_To_v1beta1_ClusterResourcesSyncCondition is an autogenerated conversion function.
func Convert_search_ClusterResourcesSyncCondition_To_v1beta1_ClusterResourcesSyncCondition(in *search.ClusterResourcesSyncCondition, out *ClusterResourcesSyncCondition, s conversion.Scope) error {
	return autoConvert_search_ClusterResourcesSyncCondition_To_v1beta1_ClusterResourcesSyncCondition(in, out, s)
}

func autoConvert_v1beta1_FieldSelector_To_search_FieldSelector(in *FieldSelector, out *search.FieldSelector, s conversion.Scope) error {
	out.MatchFields = *(*map[string]string)(unsafe.Pointer(&in.MatchFields))
	out.SeverSupported = in.SeverSupported
	return nil
}

// Convert_v1beta1_FieldSelector_To_search_FieldSelector is an autogenerated conversion function.
func Convert_v1beta1_FieldSelector_To_search_FieldSelector(in *FieldSelector, out *search.FieldSelector, s conversion.Scope) error {
	return autoConvert_v1beta1_FieldSelector_To_search_FieldSelector(in, out, s)
}

func autoConvert_search_FieldSelector_To_v1beta1_FieldSelector(in *search.FieldSelector, out *FieldSelector, s conversion.Scope) error {
	out.MatchFields = *(*map[string]string)(unsafe.Pointer(&in.MatchFields))
	out.SeverSupported = in.SeverSupported
	return nil
}

// Convert_search_FieldSelector_To_v1beta1_FieldSelector is an autogenerated conversion function.
func Convert_search_FieldSelector_To_v1beta1_FieldSelector(in *search.FieldSelector, out *FieldSelector, s conversion.Scope) error {
	return autoConvert_search_FieldSelector_To_v1beta1_FieldSelector(in, out, s)
}

func autoConvert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition(in *ResourceSyncCondition, out *search.ResourceSyncCondition, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Status = in.Status
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition is an autogenerated conversion function.
func Convert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition(in *ResourceSyncCondition, out *search.ResourceSyncCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceSyncCondition_To_search_ResourceSyncCondition(in, out, s)
}

func autoConvert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition(in *search.ResourceSyncCondition, out *ResourceSyncCondition, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Status = in.Status
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition is an autogenerated conversion function.
func Convert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition(in *search.ResourceSyncCondition, out *ResourceSyncCondition, s conversion.Scope) error {
	return autoConvert_search_ResourceSyncCondition_To_v1beta1_ResourceSyncCondition(in, out, s)
}

func autoConvert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule(in *ResourceSyncRule, out *search.ResourceSyncRule, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Resource = in.Resource
	out.Namespace = in.Namespace
	out.ResyncPeriod = (*v1.Duration)(unsafe.Pointer(in.ResyncPeriod))
	out.Selectors = *(*[]search.Selector)(unsafe.Pointer(&in.Selectors))
	out.Transform = (*search.TransformRuleSpec)(unsafe.Pointer(in.Transform))
	out.TransformRefName = in.TransformRefName
	return nil
}

// Convert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule is an autogenerated conversion function.
func Convert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule(in *ResourceSyncRule, out *search.ResourceSyncRule, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceSyncRule_To_search_ResourceSyncRule(in, out, s)
}

func autoConvert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule(in *search.ResourceSyncRule, out *ResourceSyncRule, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Resource = in.Resource
	out.Namespace = in.Namespace
	out.ResyncPeriod = (*v1.Duration)(unsafe.Pointer(in.ResyncPeriod))
	out.Selectors = *(*[]Selector)(unsafe.Pointer(&in.Selectors))
	out.Transform = (*TransformRuleSpec)(unsafe.Pointer(in.Transform))
	out.TransformRefName = in.TransformRefName
	return nil
}

// Convert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule is an autogenerated conversion function.
func Convert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule(in *search.ResourceSyncRule, out *ResourceSyncRule, s conversion.Scope) error {
	return autoConvert_search_ResourceSyncRule_To_v1beta1_ResourceSyncRule(in, out, s)
}

func autoConvert_v1beta1_Selector_To_search_Selector(in *Selector, out *search.Selector, s conversion.Scope) error {
	out.LabelSelector = (*v1.LabelSelector)(unsafe.Pointer(in.LabelSelector))
	out.FieldSelector = (*search.FieldSelector)(unsafe.Pointer(in.FieldSelector))
	return nil
}

// Convert_v1beta1_Selector_To_search_Selector is an autogenerated conversion function.
func Convert_v1beta1_Selector_To_search_Selector(in *Selector, out *search.Selector, s conversion.Scope) error {
	return autoConvert_v1beta1_Selector_To_search_Selector(in, out, s)
}

func autoConvert_search_Selector_To_v1beta1_Selector(in *search.Selector, out *Selector, s conversion.Scope) error {
	out.LabelSelector = (*v1.LabelSelector)(unsafe.Pointer(in.LabelSelector))
	out.FieldSelector = (*FieldSelector)(unsafe.Pointer(in.FieldSelector))
	return nil
}

// Convert_search_Selector_To_v1beta1_Selector is an autogenerated conversion function.
func Convert_search_Selector_To_v1beta1_Selector(in *search.Selector, out *Selector, s conversion.Scope) error {
	return autoConvert_search_Selector_To_v1beta1_Selector(in, out, s)
}

func autoConvert_v1beta1_SyncRegistry_To_search_SyncRegistry(in *SyncRegistry, out *search.SyncRegistry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SyncRegistrySpec_To_search_SyncRegistrySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SyncRegistryStatus_To_search_SyncRegistryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SyncRegistry_To_search_SyncRegistry is an autogenerated conversion function.
func Convert_v1beta1_SyncRegistry_To_search_SyncRegistry(in *SyncRegistry, out *search.SyncRegistry, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncRegistry_To_search_SyncRegistry(in, out, s)
}

func autoConvert_search_SyncRegistry_To_v1beta1_SyncRegistry(in *search.SyncRegistry, out *SyncRegistry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_search_SyncRegistrySpec_To_v1beta1_SyncRegistrySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_search_SyncRegistryStatus_To_v1beta1_SyncRegistryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_search_SyncRegistry_To_v1beta1_SyncRegistry is an autogenerated conversion function.
func Convert_search_SyncRegistry_To_v1beta1_SyncRegistry(in *search.SyncRegistry, out *SyncRegistry, s conversion.Scope) error {
	return autoConvert_search_SyncRegistry_To_v1beta1_SyncRegistry(in, out, s)
}

func autoConvert_v1beta1_SyncRegistryList_To_search_SyncRegistryList(in *SyncRegistryList, out *search.SyncRegistryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]search.SyncRegistry, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_SyncRegistry_To_search_SyncRegistry(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_SyncRegistryList_To_search_SyncRegistryList is an autogenerated conversion function.
func Convert_v1beta1_SyncRegistryList_To_search_SyncRegistryList(in *SyncRegistryList, out *search.SyncRegistryList, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncRegistryList_To_search_SyncRegistryList(in, out, s)
}

func autoConvert_search_SyncRegistryList_To_v1beta1_SyncRegistryList(in *search.SyncRegistryList, out *SyncRegistryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SyncRegistry, len(*in))
		for i := range *in {
			if err := Convert_search_SyncRegistry_To_v1beta1_SyncRegistry(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_search_SyncRegistryList_To_v1beta1_SyncRegistryList is an autogenerated conversion function.
func Convert_search_SyncRegistryList_To_v1beta1_SyncRegistryList(in *search.SyncRegistryList, out *SyncRegistryList, s conversion.Scope) error {
	return autoConvert_search_SyncRegistryList_To_v1beta1_SyncRegistryList(in, out, s)
}

func autoConvert_v1beta1_SyncRegistrySpec_To_search_SyncRegistrySpec(in *SyncRegistrySpec, out *search.SyncRegistrySpec, s conversion.Scope) error {
	out.Clusters = *(*[]string)(unsafe.Pointer(&in.Clusters))
	out.ClusterLabelSelector = (*v1.LabelSelector)(unsafe.Pointer(in.ClusterLabelSelector))
	out.SyncResources = *(*[]search.ResourceSyncRule)(unsafe.Pointer(&in.SyncResources))
	out.SyncResourcesRefName = in.SyncResourcesRefName
	return nil
}

// Convert_v1beta1_SyncRegistrySpec_To_search_SyncRegistrySpec is an autogenerated conversion function.
func Convert_v1beta1_SyncRegistrySpec_To_search_SyncRegistrySpec(in *SyncRegistrySpec, out *search.SyncRegistrySpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncRegistrySpec_To_search_SyncRegistrySpec(in, out, s)
}

func autoConvert_search_SyncRegistrySpec_To_v1beta1_SyncRegistrySpec(in *search.SyncRegistrySpec, out *SyncRegistrySpec, s conversion.Scope) error {
	out.ClusterLabelSelector = (*v1.LabelSelector)(unsafe.Pointer(in.ClusterLabelSelector))
	out.Clusters = *(*[]string)(unsafe.Pointer(&in.Clusters))
	out.SyncResources = *(*[]ResourceSyncRule)(unsafe.Pointer(&in.SyncResources))
	out.SyncResourcesRefName = in.SyncResourcesRefName
	return nil
}

// Convert_search_SyncRegistrySpec_To_v1beta1_SyncRegistrySpec is an autogenerated conversion function.
func Convert_search_SyncRegistrySpec_To_v1beta1_SyncRegistrySpec(in *search.SyncRegistrySpec, out *SyncRegistrySpec, s conversion.Scope) error {
	return autoConvert_search_SyncRegistrySpec_To_v1beta1_SyncRegistrySpec(in, out, s)
}

func autoConvert_v1beta1_SyncRegistryStatus_To_search_SyncRegistryStatus(in *SyncRegistryStatus, out *search.SyncRegistryStatus, s conversion.Scope) error {
	out.Clusters = *(*[]search.ClusterResourcesSyncCondition)(unsafe.Pointer(&in.Clusters))
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_v1beta1_SyncRegistryStatus_To_search_SyncRegistryStatus is an autogenerated conversion function.
func Convert_v1beta1_SyncRegistryStatus_To_search_SyncRegistryStatus(in *SyncRegistryStatus, out *search.SyncRegistryStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncRegistryStatus_To_search_SyncRegistryStatus(in, out, s)
}

func autoConvert_search_SyncRegistryStatus_To_v1beta1_SyncRegistryStatus(in *search.SyncRegistryStatus, out *SyncRegistryStatus, s conversion.Scope) error {
	out.Clusters = *(*[]ClusterResourcesSyncCondition)(unsafe.Pointer(&in.Clusters))
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_search_SyncRegistryStatus_To_v1beta1_SyncRegistryStatus is an autogenerated conversion function.
func Convert_search_SyncRegistryStatus_To_v1beta1_SyncRegistryStatus(in *search.SyncRegistryStatus, out *SyncRegistryStatus, s conversion.Scope) error {
	return autoConvert_search_SyncRegistryStatus_To_v1beta1_SyncRegistryStatus(in, out, s)
}

func autoConvert_v1beta1_SyncResources_To_search_SyncResources(in *SyncResources, out *search.SyncResources, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SyncResources_To_search_SyncResources is an autogenerated conversion function.
func Convert_v1beta1_SyncResources_To_search_SyncResources(in *SyncResources, out *search.SyncResources, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncResources_To_search_SyncResources(in, out, s)
}

func autoConvert_search_SyncResources_To_v1beta1_SyncResources(in *search.SyncResources, out *SyncResources, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_search_SyncResources_To_v1beta1_SyncResources is an autogenerated conversion function.
func Convert_search_SyncResources_To_v1beta1_SyncResources(in *search.SyncResources, out *SyncResources, s conversion.Scope) error {
	return autoConvert_search_SyncResources_To_v1beta1_SyncResources(in, out, s)
}

func autoConvert_v1beta1_SyncResourcesList_To_search_SyncResourcesList(in *SyncResourcesList, out *search.SyncResourcesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]search.SyncResources)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_SyncResourcesList_To_search_SyncResourcesList is an autogenerated conversion function.
func Convert_v1beta1_SyncResourcesList_To_search_SyncResourcesList(in *SyncResourcesList, out *search.SyncResourcesList, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncResourcesList_To_search_SyncResourcesList(in, out, s)
}

func autoConvert_search_SyncResourcesList_To_v1beta1_SyncResourcesList(in *search.SyncResourcesList, out *SyncResourcesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SyncResources)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_search_SyncResourcesList_To_v1beta1_SyncResourcesList is an autogenerated conversion function.
func Convert_search_SyncResourcesList_To_v1beta1_SyncResourcesList(in *search.SyncResourcesList, out *SyncResourcesList, s conversion.Scope) error {
	return autoConvert_search_SyncResourcesList_To_v1beta1_SyncResourcesList(in, out, s)
}

func autoConvert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(in *SyncResourcesSpec, out *search.SyncResourcesSpec, s conversion.Scope) error {
	out.SyncResources = *(*[]search.ResourceSyncRule)(unsafe.Pointer(&in.SyncResources))
	return nil
}

// Convert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec is an autogenerated conversion function.
func Convert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(in *SyncResourcesSpec, out *search.SyncResourcesSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncResourcesSpec_To_search_SyncResourcesSpec(in, out, s)
}

func autoConvert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(in *search.SyncResourcesSpec, out *SyncResourcesSpec, s conversion.Scope) error {
	out.SyncResources = *(*[]ResourceSyncRule)(unsafe.Pointer(&in.SyncResources))
	return nil
}

// Convert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec is an autogenerated conversion function.
func Convert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(in *search.SyncResourcesSpec, out *SyncResourcesSpec, s conversion.Scope) error {
	return autoConvert_search_SyncResourcesSpec_To_v1beta1_SyncResourcesSpec(in, out, s)
}

func autoConvert_v1beta1_TransformRule_To_search_TransformRule(in *TransformRule, out *search.TransformRule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TransformRule_To_search_TransformRule is an autogenerated conversion function.
func Convert_v1beta1_TransformRule_To_search_TransformRule(in *TransformRule, out *search.TransformRule, s conversion.Scope) error {
	return autoConvert_v1beta1_TransformRule_To_search_TransformRule(in, out, s)
}

func autoConvert_search_TransformRule_To_v1beta1_TransformRule(in *search.TransformRule, out *TransformRule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_search_TransformRule_To_v1beta1_TransformRule is an autogenerated conversion function.
func Convert_search_TransformRule_To_v1beta1_TransformRule(in *search.TransformRule, out *TransformRule, s conversion.Scope) error {
	return autoConvert_search_TransformRule_To_v1beta1_TransformRule(in, out, s)
}

func autoConvert_v1beta1_TransformRuleList_To_search_TransformRuleList(in *TransformRuleList, out *search.TransformRuleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]search.TransformRule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_TransformRuleList_To_search_TransformRuleList is an autogenerated conversion function.
func Convert_v1beta1_TransformRuleList_To_search_TransformRuleList(in *TransformRuleList, out *search.TransformRuleList, s conversion.Scope) error {
	return autoConvert_v1beta1_TransformRuleList_To_search_TransformRuleList(in, out, s)
}

func autoConvert_search_TransformRuleList_To_v1beta1_TransformRuleList(in *search.TransformRuleList, out *TransformRuleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]TransformRule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_search_TransformRuleList_To_v1beta1_TransformRuleList is an autogenerated conversion function.
func Convert_search_TransformRuleList_To_v1beta1_TransformRuleList(in *search.TransformRuleList, out *TransformRuleList, s conversion.Scope) error {
	return autoConvert_search_TransformRuleList_To_v1beta1_TransformRuleList(in, out, s)
}

func autoConvert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(in *TransformRuleSpec, out *search.TransformRuleSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.ValueTemplate = in.ValueTemplate
	return nil
}

// Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec is an autogenerated conversion function.
func Convert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(in *TransformRuleSpec, out *search.TransformRuleSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TransformRuleSpec_To_search_TransformRuleSpec(in, out, s)
}

func autoConvert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(in *search.TransformRuleSpec, out *TransformRuleSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.ValueTemplate = in.ValueTemplate
	return nil
}

// Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec is an autogenerated conversion function.
func Convert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(in *search.TransformRuleSpec, out *TransformRuleSpec, s conversion.Scope) error {
	return autoConvert_search_TransformRuleSpec_To_v1beta1_TransformRuleSpec(in, out, s)
}

func autoConvert_v1beta1_UniResource_To_search_UniResource(in *UniResource, out *search.UniResource, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_UniResource_To_search_UniResource is an autogenerated conversion function.
func Convert_v1beta1_UniResource_To_search_UniResource(in *UniResource, out *search.UniResource, s conversion.Scope) error {
	return autoConvert_v1beta1_UniResource_To_search_UniResource(in, out, s)
}

func autoConvert_search_UniResource_To_v1beta1_UniResource(in *search.UniResource, out *UniResource, s conversion.Scope) error {
	return nil
}

// Convert_search_UniResource_To_v1beta1_UniResource is an autogenerated conversion function.
func Convert_search_UniResource_To_v1beta1_UniResource(in *search.UniResource, out *UniResource, s conversion.Scope) error {
	return autoConvert_search_UniResource_To_v1beta1_UniResource(in, out, s)
}

func autoConvert_v1beta1_UniResourceList_To_search_UniResourceList(in *UniResourceList, out *search.UniResourceList, s conversion.Scope) error {
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]runtime.Object, len(*in))
		for i := range *in {
			if err := runtime.Convert_runtime_RawExtension_To_runtime_Object(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_UniResourceList_To_search_UniResourceList is an autogenerated conversion function.
func Convert_v1beta1_UniResourceList_To_search_UniResourceList(in *UniResourceList, out *search.UniResourceList, s conversion.Scope) error {
	return autoConvert_v1beta1_UniResourceList_To_search_UniResourceList(in, out, s)
}

func autoConvert_search_UniResourceList_To_v1beta1_UniResourceList(in *search.UniResourceList, out *UniResourceList, s conversion.Scope) error {
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			if err := runtime.Convert_runtime_Object_To_runtime_RawExtension(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_search_UniResourceList_To_v1beta1_UniResourceList is an autogenerated conversion function.
func Convert_search_UniResourceList_To_v1beta1_UniResourceList(in *search.UniResourceList, out *UniResourceList, s conversion.Scope) error {
	return autoConvert_search_UniResourceList_To_v1beta1_UniResourceList(in, out, s)
}
