apiVersion: v1
data:
  config: |-
    apiVersion: v1
    clusters:
      - cluster:
          insecure-skip-tls-verify: true
          server: https://karbour-server.karbour.svc:7443
        name: karbour
    contexts:
      - context:
          cluster: karbour
          user: karbour
        name: karbour
    current-context: karbour
    kind: Config
    users:
      - name: karbour
        user:
          username: u1
          password: p1
kind: ConfigMap
metadata:
  name: karbour-kubeconfig
  namespace: karbour
