apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: karbour
spec:
  ports:
    - port: 9200
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: karbour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
            - name: KIBANA_PASSWORD
              value: dangerous0
            - name: ELASTIC_PASSWORD
              value: elastic
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
              ephemeral-storage: 10Gi
            requests:
              cpu: "2"
              memory: 4Gi
              ephemeral-storage: 10Gi
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      volumes:
        - emptyDir: { }
          name: data
