apiVersion: v1
kind: Service
metadata:
  name: karbour-server
  namespace: karbour
spec:
  ports:
    - port: 7443
  selector:
    app: karbour-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karbour-server
  name: karbour-server
  namespace: karbour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karbour-server
  template:
    metadata:
      labels:
        app: karbour-server
    spec:
      containers:
        - args:
            - --feature-gates=APIPriorityAndFairness=false
            - --disable-admission-plugins=MutatingAdmissionWebhook,NamespaceLifecycle,ValidatingAdmissionWebhook,ValidatingAdmissionPolicy
            - --cors-allowed-origins=.*
            - --search-storage-type=elasticsearch
            - --elastic-search-addresses=http://elasticsearch.karbour.svc:9200
            - --etcd-servers=http://etcd.karbour.svc:2379
            - --secure-port=7443
          command:
            - /karbour
          image: kusionstack/karbour:latest
          name: karbour-server
          ports:
            - containerPort: 7443
