apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karpor-admin
rules:
  - nonResourceURLs:
      - /rest-api/v1/resource-group-rule
      - /rest-api/v1/resource-group-rule/*
      - /rest-api/v1/cluster
      - /rest-api/v1/cluster/*
    verbs:
      - '*'
  - nonResourceURLs:
      - /
      - /rest-api/*
      - /endpoints
      - /public/*
      - /docs/*
      - /server-configs
      - /search
      - /search/*
      - /insight
      - /insight/*
      - /insightDetail
      - /insightDetail/*
      - /cluster
      - /cluster/*
      - /login
      - /rest-api/v1/authn
      - /livez
      - /readyz
    verbs:
      - get
