name: Community Planning Updater

on:
  # Trigger on milestone events
  milestone:
    types: [created, edited, deleted]
  # Trigger on issue events
  issues:
    types: [opened, edited, deleted, transferred, milestoned, demilestoned, labeled, unlabeled, assigned, unassigned]

jobs:
  osp-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Community Planning Updater
        uses: elliotxx/osp-action@v1
        with:
          # Optional: version of OSP to use (default: latest)
          version: 'latest'

          # Optional: working directory (default: project root)
          working-directory: '.'

          # Optional: GitHub token (default: ${{ github.token }})
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # Optional: skip caching (default: false)
          skip-cache: false

          # Optional: enable debug mode
          debug: false

          # Optional: additional OSP arguments
          args: >-
            plan
            --priority-labels priority/critical,priority/important-soon,priority/important-longterm,priority/awaiting-more-evidence
            --category-labels area/cli,area/ai,area/search,area/insight,area/cluster-mgmt,area/experience,area/installation,area/performance,area/server,area/storage,area/syncer,bug,chore,enhancement,governance,security,testing,logistics,integration,documentation,growth
